export const mockPosts = [
  {
    id: "post1",
    title: "10 Tips for Better Productivity",
    thumbnail: "/placeholder.svg?height=200&width=360",
    platform: "YouTube",
    date: "2 days ago",
    caption:
      "In this video, I share my top 10 productivity tips that have helped me stay focused and get more done. These strategies have transformed my workflow and can help you too!",
    likes: 1245,
    comments: 89,
    views: "24.5K",
    url: "#",
  },
  {
    id: "post2",
    title: "My Morning Routine Revealed",
    thumbnail: "/placeholder.svg?height=200&width=360",
    platform: "Instagram",
    date: "5 days ago",
    caption:
      "Ever wondered how I start my day? Here's a behind-the-scenes look at my morning routine that sets me up for success every day.",
    likes: 3782,
    comments: 156,
    views: "42.1K",
    url: "#",
  },
  {
    id: "post3",
    title: "Why I Switched to This Camera",
    thumbnail: "/placeholder.svg?height=200&width=360",
    platform: "YouTube",
    date: "1 week ago",
    caption:
      "After years of using my old setup, I finally made the switch to this camera. Here's why I made the change and my honest review after using it for a month.",
    likes: 876,
    comments: 64,
    views: "18.9K",
    url: "#",
  },
]

export const mockComments = [
  {
    id: "comment1",
    author: {
      name: "Alex Johnson",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    text: "This video was exactly what I needed! Your productivity tips have already helped me organize my day better. Can't wait to see more content like this!",
    platform: "youtube",
    time: "2 hours ago",
    likes: 24,
    replies: 3,
    flagged: false,
    needsAttention: false,
    archived: false,
    postId: "post1",
    postTitle: "10 Tips for Better Productivity",
    postThumbnail: "/placeholder.svg?height=40&width=40",
    emotion: "excited",
    sentiment: "positive",
    category: "general",
  },
  {
    id: "comment2",
    author: {
      name: "Sarah Miller",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    text: "I disagree with tip #7. It might work for some people, but it's definitely not a one-size-fits-all solution. Would love to hear your thoughts on alternatives.",
    platform: "youtube",
    time: "5 hours ago",
    likes: 8,
    replies: 1,
    flagged: false,
    needsAttention: true,
    archived: false,
    postId: "post1",
    postTitle: "10 Tips for Better Productivity",
    postThumbnail: "/placeholder.svg?height=40&width=40",
    emotion: "curious",
    sentiment: "negative",
    category: "product",
  },
  {
    id: "comment3",
    author: {
      name: "Mike Thompson",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    text: "Have you tried the Pomodoro technique? I'd love to see a video specifically about that method and how you would implement it.",
    platform: "youtube",
    time: "1 day ago",
    likes: 42,
    replies: 5,
    flagged: false,
    needsAttention: false,
    archived: false,
    postId: "post1",
    postTitle: "10 Tips for Better Productivity",
    postThumbnail: "/placeholder.svg?height=40&width=40",
    emotion: "curious",
    sentiment: "neutral",
    category: "product",
  },
  {
    id: "comment4",
    author: {
      name: "Emily Chen",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    text: "Your morning routine is so inspiring! I've been trying to wake up earlier but struggle with consistency. Any tips for making it a habit?",
    platform: "instagram",
    time: "3 days ago",
    likes: 15,
    replies: 2,
    flagged: false,
    needsAttention: false,
    archived: false,
    postId: "post2",
    postTitle: "My Morning Routine Revealed",
    postThumbnail: "/placeholder.svg?height=40&width=40",
    emotion: "excited",
    sentiment: "positive",
    category: "general",
  },
  {
    id: "comment5",
    author: {
      name: "David Wilson",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    text: "This is complete garbage. You're just copying other creators and pretending these are your original ideas. Unsubscribed!",
    platform: "youtube",
    time: "4 days ago",
    likes: 3,
    replies: 7,
    flagged: true,
    needsAttention: true,
    archived: false,
    postId: "post1",
    postTitle: "10 Tips for Better Productivity",
    postThumbnail: "/placeholder.svg?height=40&width=40",
    emotion: "angry",
    sentiment: "negative",
    category: "spam",
  },
  {
    id: "comment6",
    author: {
      name: "Jessica Lee",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    text: "What camera settings do you use for indoor shots? The lighting in your videos is always perfect!",
    platform: "youtube",
    time: "6 days ago",
    likes: 28,
    replies: 1,
    flagged: false,
    needsAttention: false,
    archived: false,
    postId: "post3",
    postTitle: "Why I Switched to This Camera",
    postThumbnail: "/placeholder.svg?height=40&width=40",
    emotion: "curious",
    sentiment: "positive",
    category: "product",
  },
  {
    id: "comment7",
    author: {
      name: "Ryan Garcia",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    text: "I bought this camera because of your recommendation and I'm so disappointed. The battery life is terrible and the image quality isn't as good as you claimed.",
    platform: "youtube",
    time: "1 week ago",
    likes: 5,
    replies: 2,
    flagged: false,
    needsAttention: true,
    archived: false,
    postId: "post3",
    postTitle: "Why I Switched to This Camera",
    postThumbnail: "/placeholder.svg?height=40&width=40",
    emotion: "angry",
    sentiment: "negative",
    category: "product",
  },
  {
    id: "comment8",
    author: {
      name: "Olivia Brown",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    text: "Your content has been so helpful for me as I start my own channel. Would you ever consider doing one-on-one coaching sessions?",
    platform: "instagram",
    time: "1 week ago",
    likes: 37,
    replies: 1,
    flagged: false,
    needsAttention: false,
    archived: false,
    postId: "post2",
    postTitle: "My Morning Routine Revealed",
    postThumbnail: "/placeholder.svg?height=40&width=40",
    emotion: "happy",
    sentiment: "positive",
    category: "vip",
  },
  {
    id: "comment9",
    author: {
      name: "Chris Taylor",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    text: "I've been following your channel for years and the quality just keeps getting better. This camera upgrade was definitely worth it - the footage looks amazing!",
    platform: "youtube",
    time: "1 week ago",
    likes: 52,
    replies: 0,
    flagged: false,
    needsAttention: false,
    archived: false,
    postId: "post3",
    postTitle: "Why I Switched to This Camera",
    postThumbnail: "/placeholder.svg?height=40&width=40",
    emotion: "excited",
    sentiment: "positive",
    category: "vip",
  },
  {
    id: "comment10",
    author: {
      name: "Sophia Martinez",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    text: "Do you have any recommendations for productivity apps that sync across devices? I'm trying to streamline my workflow between my phone and laptop.",
    platform: "youtube",
    time: "1 week ago",
    likes: 19,
    replies: 3,
    flagged: false,
    needsAttention: false,
    archived: false,
    postId: "post1",
    postTitle: "10 Tips for Better Productivity",
    postThumbnail: "/placeholder.svg?height=40&width=40",
    emotion: "curious",
    sentiment: "neutral",
    category: "general",
  },
]
